### ISSUE TITLE
License of the library?

### ISSUE THREAD

**Issue by mupuf** [ilkermanap/python-pciids#1]
Hey,

I would like to use your classes, but I can't until you define a license for it. I would be biased towards an MIT license but really, I just need to be able to add a CLI interface (which I would contribute back to you) and redistribute it.

**Comment by mupuf** [comment]
Sorry, pressed enter too quickly.

Thanks in advance!
Martin

**Comment by ilkermanap** [comment]
Hello, 
Sorry for late reply, it is not noticed because of heavy volume of messages from another project. 
Here is the MIT license, if you still want to use the code.

Regards
